# Generated by Django 3.2.7 on 2021-09-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cvClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
                ('city', models.CharField(max_length=150)),
                ('diskription', models.TextField(blank=True)),
                ('time_guest', models.DateTimeField(default=False)),
            ],
        ),
    ]
