# Generated by Django 3.2.7 on 2021-09-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0003_auto_20210928_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvclient',
            name='time_guest',
            field=models.DateTimeField(),
        ),
    ]
