# Generated by Django 3.2.7 on 2021-09-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0002_alter_cvclient_time_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvclient',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cvclient',
            name='time_guest',
            field=models.DateTimeField(blank=True),
        ),
    ]
