# Generated by Django 3.2.7 on 2021-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0004_alter_cvclient_time_guest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvclient',
            options={'ordering': ['-time_guest', 'client_name'], 'verbose_name': 'Гостей', 'verbose_name_plural': 'Гость'},
        ),
        migrations.AlterField(
            model_name='cvclient',
            name='city',
            field=models.CharField(max_length=150, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='cvclient',
            name='client_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='cvclient',
            name='diskription',
            field=models.TextField(blank=True, verbose_name='Пожелания'),
        ),
        migrations.AlterField(
            model_name='cvclient',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='cvclient',
            name='time_guest',
            field=models.DateTimeField(verbose_name='Дата записи'),
        ),
    ]
